# Site settings
title:       dm-nesteroff <br><small>in progress...</small>
email:       hello@nesteroff.com
author:      freemiumhead
description: ""
baseurl:     ""
url:         "http://nesteroff.com"
date_format: "%d-%m-%Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: dm-nesteroff

# Social icons
github_username: freemiumhead
bitbucket_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: ''
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
